version: '2'
services:
  jenkins:
    # image: 'bitnami/jenkins:2'
    # user: user
    # password: bitnami
    build: .
    ports:
      - '8080:8080'
      - '50000:50000'
    privileged: true
    volumes:
      - 'jenkins_data:/bitnami'
      - '/var/run/docker.sock:/var/run/docker.sock'
volumes:
  jenkins_data:
    driver: local
